package cloudflare

import (
	"bytes"
	"text/template"

	"github.com/distlanglabs/distlang/pkg/artifacts"
	v8backend "github.com/distlanglabs/distlang/pkg/backend/v8"
)

// Context supplies template data for Cloudflare artifacts.
type Context struct {
	ProjectName   string
	KVBindingName string
	KVNamespaceID string
	KVPreviewID   string
	StoreBaseURL  string
	HelpersMode   string
}

// Package renders Cloudflare provider artifacts from V8 backend output.
func Package(out v8backend.Output, ctx Context) ([]artifacts.Artifact, error) {
	if ctx.KVBindingName == "" {
		ctx.KVBindingName = "DISTLANG_KV"
	}

	wrangler, err := renderTemplate(wranglerTomlTmpl, ctx)
	if err != nil {
		return nil, err
	}

	makefile, err := renderTemplate(makefileTmpl, ctx)
	if err != nil {
		return nil, err
	}

	items := []artifacts.Artifact{
		{Path: "dist/cloudflare/worker.js", Content: []byte(out.Emitted)},
		{Path: "dist/cloudflare/wrangler.toml", Content: []byte(wrangler)},
		{Path: "dist/cloudflare/Makefile", Content: []byte(makefile)},
	}

	return items, nil
}

func renderTemplate(src string, data any) (string, error) {
	tmpl, err := template.New("tmpl").Parse(src)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

const wranglerTomlTmpl = `# Generated by distlang. Edits may be overwritten.
name = "{{.ProjectName}}"
main = "worker.js"
compatibility_date = "2024-01-01"
{{- if .KVNamespaceID }}

[[kv_namespaces]]
binding = "{{.KVBindingName}}"
id = "{{.KVNamespaceID}}"
{{- if .KVPreviewID }}
preview_id = "{{.KVPreviewID}}"
{{- end }}
{{- end }}
{{- if or .StoreBaseURL .HelpersMode }}

[vars]
{{- if .StoreBaseURL }}
DISTLANG_STORE_BASE_URL = "{{.StoreBaseURL}}"
{{- end }}
{{- if .HelpersMode }}
DISTLANG_HELPERS_MODE = "{{.HelpersMode}}"
{{- end }}
{{- end }}
`

const makefileTmpl = `# Generated by distlang. Edits may be overwritten.

.PHONY: deps check-tools build run publish tail clean

deps:
	@command -v wrangler >/dev/null 2>&1 && echo "wrangler already installed" && exit 0 || true
	@command -v npm >/dev/null 2>&1 || (echo "npm not installed" && exit 1)
	@npm install -g wrangler

check-tools: deps
	@command -v wrangler >/dev/null 2>&1 || (echo "wrangler not installed" && exit 1)

build: check-tools
	# wrangler deploy --dry-run bundles/validates only (no publish)
	wrangler deploy --dry-run

run: check-tools
	wrangler dev

publish: check-tools
	wrangler deploy

tail: check-tools
	wrangler tail

clean:
	rm -rf .wrangler state
`
